export const API = {
    navLinks: "nav-links.json",
    footerOtherLinks: "footer-other-links.json",
    footerInfo: "footer-info.json",
    sliderImages: "slider-images.json",
    authorSocials: "author-socials.json",
    keyFeatures: "feature-items.json",
    //products: "products.json",
    products: "api/products",
    //productCategories: "product-categories.json",
    productCategories: "api/categories",
    //ingredients: "ingredients.json",
    ingredients: "api/ingredients",
    login: "api/auth",
    register: "api/register",
    contact: "api/contact",
    cart: "api/cart",
    orders: "api/orders",
    addons: "api/addons",
    auditLog: "api/auditlog",
    users: "api/users"
};